### PR TITLE
Plone 5

### PR DESCRIPTION
**Pull request by tomgross**
Modernize package
- Test on Travis-CI
- Add code-analysis
- Make tests run on Plone 5
- Port JavaScript to ResourceRegistry

### CODE REVIEW

**Comment by pbauer** [comment]
@tomgross for travis to use up the right python you need to do the same as https://github.com/plone/bobtemplates.plone/pull/230/files. Other than that: 👍

**Comment by tomgross** [comment]
@pbauer We finally did it 😉 Thanks for the review and the fix.

**Comment by tomgross** [comment]
@laulaz mind to review, merge and release as 2.0 beta?

**Comment by laulaz** [comment]
It has been merged and released as https://pypi.org/project/collective.geotransform/2.0a1/

**Pull request merged**
